# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import voiceguard_pb2 as voiceguard__pb2  # fixup: see proto/__init__.py

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voiceguard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceGuardStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/voiceguard.v1.VoiceGuard/CreateSession',
                request_serializer=voiceguard__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.SessionState.FromString,
                _registered_method=True)
        self.UpdateContext = channel.unary_unary(
                '/voiceguard.v1.VoiceGuard/UpdateContext',
                request_serializer=voiceguard__pb2.UpdateContextRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.ContextState.FromString,
                _registered_method=True)
        self.Enroll = channel.unary_unary(
                '/voiceguard.v1.VoiceGuard/Enroll',
                request_serializer=voiceguard__pb2.EnrollRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.Analyze = channel.unary_unary(
                '/voiceguard.v1.VoiceGuard/Analyze',
                request_serializer=voiceguard__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.Assessment.FromString,
                _registered_method=True)
        self.Acknowledge = channel.unary_unary(
                '/voiceguard.v1.VoiceGuard/Acknowledge',
                request_serializer=voiceguard__pb2.AcknowledgeRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.AcknowledgeResponse.FromString,
                _registered_method=True)
        self.GetAudit = channel.unary_unary(
                '/voiceguard.v1.VoiceGuard/GetAudit',
                request_serializer=voiceguard__pb2.GetAuditRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.AuditTrail.FromString,
                _registered_method=True)
        self.StreamAudio = channel.stream_stream(
                '/voiceguard.v1.VoiceGuard/StreamAudio',
                request_serializer=voiceguard__pb2.AudioChunk.SerializeToString,
                response_deserializer=voiceguard__pb2.Assessment.FromString,
                _registered_method=True)


class VoiceGuardServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """POST /api/session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateContext(self, request, context):
        """POST /api/session/{sid}/context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enroll(self, request, context):
        """POST /api/session/{sid}/enroll
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """POST /api/session/{sid}/analyze -- one clip in, one assessment out
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Acknowledge(self, request, context):
        """POST /api/session/{sid}/acknowledge
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAudit(self, request, context):
        """GET /api/session/{sid}/audit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request_iterator, context):
        """WS /api/session/{sid}/stream -- client streams raw PCM chunks, server
        streams back one Assessment per hop (~0.5s of new audio), same as the
        WebSocket path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceGuardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=voiceguard__pb2.CreateSessionRequest.FromString,
                    response_serializer=voiceguard__pb2.SessionState.SerializeToString,
            ),
            'UpdateContext': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateContext,
                    request_deserializer=voiceguard__pb2.UpdateContextRequest.FromString,
                    response_serializer=voiceguard__pb2.ContextState.SerializeToString,
            ),
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=voiceguard__pb2.EnrollRequest.FromString,
                    response_serializer=voiceguard__pb2.EnrollResponse.SerializeToString,
            ),
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=voiceguard__pb2.AnalyzeRequest.FromString,
                    response_serializer=voiceguard__pb2.Assessment.SerializeToString,
            ),
            'Acknowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.Acknowledge,
                    request_deserializer=voiceguard__pb2.AcknowledgeRequest.FromString,
                    response_serializer=voiceguard__pb2.AcknowledgeResponse.SerializeToString,
            ),
            'GetAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudit,
                    request_deserializer=voiceguard__pb2.GetAuditRequest.FromString,
                    response_serializer=voiceguard__pb2.AuditTrail.SerializeToString,
            ),
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=voiceguard__pb2.AudioChunk.FromString,
                    response_serializer=voiceguard__pb2.Assessment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voiceguard.v1.VoiceGuard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voiceguard.v1.VoiceGuard', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceGuard:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.v1.VoiceGuard/CreateSession',
            voiceguard__pb2.CreateSessionRequest.SerializeToString,
            voiceguard__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.v1.VoiceGuard/UpdateContext',
            voiceguard__pb2.UpdateContextRequest.SerializeToString,
            voiceguard__pb2.ContextState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.v1.VoiceGuard/Enroll',
            voiceguard__pb2.EnrollRequest.SerializeToString,
            voiceguard__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.v1.VoiceGuard/Analyze',
            voiceguard__pb2.AnalyzeRequest.SerializeToString,
            voiceguard__pb2.Assessment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Acknowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.v1.VoiceGuard/Acknowledge',
            voiceguard__pb2.AcknowledgeRequest.SerializeToString,
            voiceguard__pb2.AcknowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.v1.VoiceGuard/GetAudit',
            voiceguard__pb2.GetAuditRequest.SerializeToString,
            voiceguard__pb2.AuditTrail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voiceguard.v1.VoiceGuard/StreamAudio',
            voiceguard__pb2.AudioChunk.SerializeToString,
            voiceguard__pb2.Assessment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
